# Generated by Django 5.1.3 on 2025-05-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appointment_reason_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selling',
            name='approved',
        ),
        migrations.AddField(
            model_name='selling',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='c34e4d', max_length=6),
        ),
    ]
