# Generated by Django 5.1.3 on 2025-06-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customuser_address_customuser_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='selling',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='f24f43', max_length=6),
        ),
    ]
