# Generated by Django 5.1.3 on 2025-06-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_selling_address_selling_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='d7b93e', max_length=6),
        ),
        migrations.AlterField(
            model_name='selling',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
