# Generated by Django 5.1.3 on 2025-06-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_otptoken_otp_code_alter_selling_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selling',
            name='image1',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='1b9482', max_length=6),
        ),
    ]
