# Generated by Django 5.1.3 on 2025-11-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_productvariation_image_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='96f905', max_length=6),
        ),
    ]
