# Generated by Django 5.1.3 on 2025-11-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_productvariation_description_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='component_type',
            field=models.CharField(choices=[('cpu', 'Processor'), ('motherboard', 'Motherboard'), ('ram', 'RAM'), ('gpu', 'Graphics Card'), ('psu', 'Power Supply'), ('case', 'PC Case'), ('cooling', 'Cooling'), ('monitor', 'Monitor'), ('storage', 'Storage')], default='motherboard', max_length=50),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='dbc2f6', max_length=6),
        ),
    ]
