# Generated by Django 5.2.4 on 2025-11-26 04:50

from django.db import migrations, models
from django.db.models import Count


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_otptoken_otp_code_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='be89a7', max_length=6),
        ),
        # Remove duplicate ProductReview rows (keep the earliest) before
        # applying the unique_together constraint. This prevents migration
        # failures when duplicate (user, product) pairs already exist.
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                (lambda ProductReview: [
                    (lambda qs: [qs.exclude(pk=qs.first().pk).delete() for _ in [None]])(ProductReview.objects.filter(user_id=d['user_id'], product_id=d['product_id']).order_by('id'))
                    for d in ProductReview.objects.values('user_id','product_id').annotate(c=Count('id')).filter(c__gt=1)
                ])(apps.get_model('app', 'ProductReview'))
            ),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('user', 'product')},
        ),
    ]
