# Generated by Django 5.1.3 on 2025-11-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_oauth_pending',
            field=models.BooleanField(default=False, help_text='True if account created via OAuth but profile not completed'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='c0648b', max_length=6),
        ),
    ]
