# Generated by Django 5.1.3 on 2025-11-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_customuser_is_oauth_pending_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='4d3305', max_length=6),
        ),
    ]
