# Generated by Django 5.1.3 on 2025-12-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentproduct',
            name='variation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='a293ea', max_length=6),
        ),
    ]
