# Generated by Django 5.1.3 on 2025-12-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_appointmentproduct_variation_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='9c1fa8', max_length=6),
        ),
    ]
