# Generated by Django 5.2.10 on 2026-01-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_others_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='eeb596', max_length=6),
        ),
    ]
