# Generated by Django 5.2.10 on 2026-01-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_product_model_3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='c93591', max_length=6),
        ),
    ]
