# Generated by Django 5.2.10 on 2026-01-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='botpress_user_key',
            field=models.TextField(blank=True, help_text='Cached Botpress chat API user key', null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='318b91', max_length=6),
        ),
    ]
