# Generated by Django 5.2.10 on 2026-01-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_customuser_botpress_user_key_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='1c27de', max_length=6),
        ),
    ]
