# Generated by Django 5.2.10 on 2026-01-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_otptoken_otp_code_chatconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='build_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='61f80b', max_length=6),
        ),
    ]
