# Generated by Django 5.2.10 on 2026-01-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_chatconversation_build_state_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='f5ffa5', max_length=6),
        ),
    ]
