# Generated by Django 5.2.10 on 2026-01-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='component_type',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='a43b5a', max_length=6),
        ),
    ]
