# Generated by Django 5.2.10 on 2026-01-13 07:30

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='last_resend_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default=app.models.generate_otp_code, max_length=6),
        ),
    ]
