from django.urls import path
from .views import HomePage, ProductPage, ProductItemPage, AIBotPage, CheckoutPage, AppointmentCompletePage, SellingPage, SellingCompletePage, SellingInfoPage, MyAppointmentPage, MySellingAppointmentPage, MyCancelledAppointmentPage, MyHistoryAppointmentPage, CartPage, FavoritePage, add_to_cart, AdminDashboard, AdminInventory, AdminProduct, AdminAppointment, AdminSellingAppointment
from . import views
from .api_views import api_product_3d_model, api_search_products_with_3d, api_gemini_system_prompt, api_products_recommend, api_available_categories, api_store_info, api_save_chat_conversation, api_load_chat_conversation, api_delete_chat_conversation, firebase_signup_verify, api_serve_3d_model
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('add_product', views.addproduct, name='add_product'),
    path('product', ProductPage.as_view(), name='product'),
    path('product_item/<int:product_id>/', ProductItemPage.as_view(), name='product_item'),
    path('submit_rating/<int:product_id>/', views.submit_rating_ajax, name='submit_rating_ajax'),
    path('submit_comment/<int:product_id>/', views.submit_comment_ajax, name='submit_comment_ajax'),
    path('appointment', views.appoint, name='appointment'),
    path('get-available-times/', views.get_available_times, name='get_available_times'),
    path('get-booked-dates/', views.get_booked_dates, name='get_booked_dates'),
    path('appointing/json/', views.appointing, name='appointing'),
    path('checkout', CheckoutPage.as_view(), name='checkout'),
    path('appointment_complete', AppointmentCompletePage.as_view(), name='appointment_complete'),
    path('selling', SellingPage.as_view(), name='selling'),
    path('selling_complete', SellingCompletePage.as_view(), name='selling_complete'),
    path('selling_information', SellingInfoPage.as_view(), name='selling_information'),
    path('my_appointment', MyAppointmentPage.as_view(), name='my_appointment'),
    path('my_sellingappointment', MySellingAppointmentPage.as_view(), name='my_sellingappointment'),
    path('my_cancelledappointment', MyCancelledAppointmentPage.as_view(), name='my_cancelledappointment'),
    path('my_historyappointment', MyHistoryAppointmentPage.as_view(), name='my_historyappointment'),
    path('cart', CartPage.as_view(), name='cart'),
    path('add-to-cart/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:product_id>', views.update_cart, name='update_cart'),
    path('remove_from_cart/<int:product_id>', views.remove_from_cart, name='remove_from_cart'),
    path('direct_checkout', views.direct_checkout, name='direct_checkout'),
    path('update_direct_checkout', views.update_direct_checkout, name='update_direct_checkout'),
    path('favorite', FavoritePage.as_view(), name='favorite'),
    path('toggle_favorite/<int:product_id>/', views.toggle_favorite, name='toggle_favorite'),
    path('admin_dashboard/', AdminDashboard.as_view(), name='admin_dashboard'),
    path('admin_inventory/', AdminInventory.as_view(), name='admin_inventory'),
    path('admin_product/', AdminProduct.as_view(), name='admin_product'),
    path('add_product/', views.add_product_ajax, name='add_product'),
    path('update_product/<int:product_id>/', views.update_product_ajax, name='update_product'),
    path('api/product/<int:product_id>/', views.get_product_details, name='get_product_details'),
    path('api/product/<int:product_id>/model-3d/', api_serve_3d_model, name='api_serve_3d_model'),
    path('add_product_variant/<int:product_id>/', views.add_product_variant_ajax, name='add_product_variant'),
    path('delete_product/<int:product_id>/', views.delete_product_ajax, name='delete_product'),
    path('update_category/<int:category_id>/', views.update_category, name='update_category'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('update_brand/<int:brand_id>/', views.update_brand, name='update_brand'),
    path('delete_brand/<int:brand_id>/', views.delete_brand, name='delete_brand'),
    path('admin_appointment/', AdminAppointment.as_view(), name='admin_appointment'),
    path('admin_appointment/<int:appointment_id>/complete/', views.finished_appointment, name='finished_appointment'),
    path('admin_appointment/<int:appointment_id>/cancel/', views.cancel_appointment, name='cancel_appointment'),
    path('admin_selling/', AdminSellingAppointment.as_view(), name='admin_selling'),
    path('admin_selling/<int:selling_id>/cancel/', views.cancel_trade, name='cancel_trade'),
    path('admin_selling/<int:selling_id>/complete/', views.complete_trade, name='complete_trade'),
    path('register/', views.register, name="register"),
    path('login/', views.login_view, name="login"),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('reset-password/<int:uid>/<str:token>/', views.reset_password, name='reset_password'),
    path('profile/', views.user_profile, name='profile'),
    path('logout/', views.logout_view, name='logout'),
    path('resend_otp/', views.resend_otp, name="resend-otp"),
    path('api/firebase/signup-verify/', firebase_signup_verify, name='firebase_signup_verify'),
    path('api/gemini/system-prompt/', api_gemini_system_prompt, name='api_gemini_system_prompt'),
    path('api/products/recommend/', api_products_recommend, name='api_products_recommend'),
    path('api/categories/', api_available_categories, name='api_available_categories'),
    path('api/store-info/', api_store_info, name='api_store_info'),
    path('api/chat/save/', api_save_chat_conversation, name='api_save_chat'),
    path('api/chat/load/', api_load_chat_conversation, name='api_load_chat'),
    path('api/chat/delete/', api_delete_chat_conversation, name='api_delete_chat'),
    path('api/products/<component>/', views.product_list, name='product_list'),
    path('model_viewer/', views.model_viewer, name="model_viewer"),
    path("api/add-pc-build/", views.add_pc_build_to_cart, name="add_pc_build"),
    path('ai3d-test/', views.ai3d_test, name='ai3d_test'),
]
